---
sudo: false
language: ruby
matrix:
  fast_finish: true
  include:
  - rvm: 2.1.6
    env: PUPPET_GEM_VERSION="~> 4.0" FACTER_GEM_VERSION="~> 2.0"
  - rvm: 2.1.9
    env: PUPPET_GEM_VERSION="~> 4.0" FACTER_GEM_VERSION="~> 2.0"
  - rvm: 2.2
    env: PUPPET_GEM_VERSION="~> 4.0" FACTER_GEM_VERSION="~> 2.0"
  - rvm: 2.3.1
    env: PUPPET_GEM_VERSION="~> 4.0" FACTER_GEM_VERSION="~> 2.0"
  - rvm: 2.4.1
    env: PUPPET_GEM_VERSION="~> 4.0" FACTER_GEM_VERSION="~> 2.0"
  - rvm: 2.4.1
    env: PUPPET_GEM_VERSION="~> 5.0" FACTER_GEM_VERSION="~> 2.0" CHECK="rubocop"
script:
  - 'bundle exec rake validate'
  - 'bundle exec rake lint'
  - 'bundle exec rake spec $CHECK'
bundler_args: --without system_tests
cache: bundler
before_install:
  - bundle -v
  - rm Gemfile.lock .gemfile.lock || true
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v
notifications:
  email: false
